## Predictors for Norway

load('Norway.pr.rda')
nv <- apply(coredata(pr),2,'nv')
good <- nv > 43000
pr <- subset(pr,is=good)
pr <- subset(pr,it=c(1900,2015))
diagnose(pr)
mu <- annual(pr,FUN='wetmean',nmin=200)
fw <- annual(pr,FUN='wetfreq',nmin=200)
mu <- pcafill(mu)
fw <- pcafill(fw)
t2m <- retrieve('~/Downloads/air.mon.mean.nc',lon=c(-60,30),lat=c(20,70))
slp <- retrieve('~/Downloads/slp.mon.mean.nc',lon=c(-60,30),lat=c(20,70))
mu.pca <- PCA(mu)
fw.pca <- PCA(fw)
es <- C.C.eq(t2m)
SLP <- annual(slp)
ES <- mask(annual(es),land=TRUE)
eof.es <- EOF(ES)
eof.slp <- EOF(SLP)
ds.mu <- DS(mu.pca,eof.es)
ds.fw <- DS(fw.pca,eof.slp)
plot(ds.mu)
plot(ds.fw)
